// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"projecttemp/ent/payment"
	"projecttemp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentUpdate) SetUserID(v int64) *PaymentUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableUserID(v *int64) *PaymentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *PaymentUpdate) AddUserID(v int64) *PaymentUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetMethod sets the "method" field.
func (_u *PaymentUpdate) SetMethod(v payment.Method) *PaymentUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableMethod(v *payment.Method) *PaymentUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdate) SetStatus(v payment.Status) *PaymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableStatus(v *payment.Status) *PaymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmountCent sets the "amount_cent" field.
func (_u *PaymentUpdate) SetAmountCent(v int64) *PaymentUpdate {
	_u.mutation.ResetAmountCent()
	_u.mutation.SetAmountCent(v)
	return _u
}

// SetNillableAmountCent sets the "amount_cent" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmountCent(v *int64) *PaymentUpdate {
	if v != nil {
		_u.SetAmountCent(*v)
	}
	return _u
}

// AddAmountCent adds value to the "amount_cent" field.
func (_u *PaymentUpdate) AddAmountCent(v int64) *PaymentUpdate {
	_u.mutation.AddAmountCent(v)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *PaymentUpdate) SetSubject(v string) *PaymentUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableSubject(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentUpdate) SetPaidAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePaidAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentUpdate) ClearPaidAt() *PaymentUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdate) SetUpdatedAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := payment.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Payment.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCent(); ok {
		if err := payment.AmountCentValidator(v); err != nil {
			return &ValidationError{Name: "amount_cent", err: fmt.Errorf(`ent: validator failed for field "Payment.amount_cent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := payment.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Payment.subject": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(payment.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(payment.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(payment.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AmountCent(); ok {
		_spec.SetField(payment.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCent(); ok {
		_spec.AddField(payment.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(payment.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetUserID sets the "user_id" field.
func (_u *PaymentUpdateOne) SetUserID(v int64) *PaymentUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableUserID(v *int64) *PaymentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *PaymentUpdateOne) AddUserID(v int64) *PaymentUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetMethod sets the "method" field.
func (_u *PaymentUpdateOne) SetMethod(v payment.Method) *PaymentUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableMethod(v *payment.Method) *PaymentUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdateOne) SetStatus(v payment.Status) *PaymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableStatus(v *payment.Status) *PaymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmountCent sets the "amount_cent" field.
func (_u *PaymentUpdateOne) SetAmountCent(v int64) *PaymentUpdateOne {
	_u.mutation.ResetAmountCent()
	_u.mutation.SetAmountCent(v)
	return _u
}

// SetNillableAmountCent sets the "amount_cent" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmountCent(v *int64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmountCent(*v)
	}
	return _u
}

// AddAmountCent adds value to the "amount_cent" field.
func (_u *PaymentUpdateOne) AddAmountCent(v int64) *PaymentUpdateOne {
	_u.mutation.AddAmountCent(v)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *PaymentUpdateOne) SetSubject(v string) *PaymentUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableSubject(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentUpdateOne) SetPaidAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentUpdateOne) ClearPaidAt() *PaymentUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdateOne) SetUpdatedAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := payment.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Payment.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := payment.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Payment.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCent(); ok {
		if err := payment.AmountCentValidator(v); err != nil {
			return &ValidationError{Name: "amount_cent", err: fmt.Errorf(`ent: validator failed for field "Payment.amount_cent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := payment.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Payment.subject": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(payment.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(payment.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(payment.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AmountCent(); ok {
		_spec.SetField(payment.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCent(); ok {
		_spec.AddField(payment.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(payment.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
